version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/data

volumes:
  db_data:
  cache_data:
